name: Publish Docker Image to DockerHub
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publishe to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gkarthiks/whereami/whereami
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
